version: '3.8'

services:
  article-parser-api:
    build: .
    ports:
      - "3002:3002"
    env_file:
      - secrets.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - GUNICORN_TIMEOUT=60
      - GUNICORN_WORKERS=2