# Deploy to these servers.
servers:
  web:
    - 135.181.252.47

# Enable SSL auto certification via Let's Encrypt and allow for multiple apps on a single web server.
proxy:
  ssl: true
  host: hel-np4k.webgrab.click
  app_port: 3002
  response_timeout: 60
  healthcheck:
    path: /health
    interval: 7
    timeout: 60

# Credentials for your image host.
registry:
  username: cjulio001
  password:
    - KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  secret:
    - API_TOKEN
  clear:
    PORT: 3002
    # Set number of cores available to the application on each server (default: 1).
    WEB_CONCURRENCY: 2
    # Log level for the application
    LOG_LEVEL: info
    # Gunicorn timeout settings
    GUNICORN_TIMEOUT: 60
    GUNICORN_WORKERS: 2
    # Request timeout settings
    REQUEST_TIMEOUT: 60

# Configure the image builder.
builder:
  arch: amd64

# Use a different ssh user than root
ssh:
  user: root
  keys: [ "~/.ssh/id_rsa" ]
